Vue.component(
    'factures-list',
    require('./FacturesList.vue').default
);
Vue.component(
    'facture-create',
    require('./FactureFormCreate.vue').default
);
Vue.component(
    'facture-edit',
    require('./FactureFormEdit.vue').default
);
Vue.component(
    'facture-details',
    require('./FactureDetails.vue').default
);
Vue.component(
    'relances-facture',
    require('./RelancesFacture.vue').default
);
