Vue.component(
    'clients-list',
    require('./ClientsList.vue').default
);
Vue.component(
    'client-create',
    require('./ClientFormCreate.vue').default
);
Vue.component(
    'client-edit',
    require('./ClientFormEdit.vue').default
);
Vue.component(
    'client-details',
    require('./ClientDetails.vue').default
);
